# Base configs
baseurl: "https://b10g.navnee.tk"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Sketch by Navneethakrishnan"
subtitle: "My Artwork Collection"
author: "Navneethakrishnan"
header:
 title: "Art"
 subtitle: "by Navneet"
footer:
 name: "Hey there, my name is Navneet"
 bio: "N00b Photographer, Linux SysAdmin, Football Fanatic, Artist"
web_design: "By AJ"
social_urls:
  instagram: "https://www.instagram.com/nav.kris"
  dribbble: "https://dribbble.com/navneethakrishnan"
  linkedin: "https://in.linkedin.com/in/navneethakrishnan"
  github: "https://www.github.com/navneet-suresh"
