# Base configs
baseurl: "https://i.navnee.tk/artworks/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Navneet's Art Collection"
subtitle: "Ranging from Anime. Celebs, Nature..."
author: "Navneethakrishnan"
header:
 title: "Navneet's Art Collection"
 subtitle: "Ranging from Anime. Celebs, Nature..."
footer:
 name: "Hey there, my name is Navneet"
 bio: "Hobby Artist"
web_design: "By AJ and Jekylled by Ram Patra"
social_urls:
  instagram: "https://www.instagram.com/nav.kris"
  dribbble: "https://dribbble.com/navneethakrishnan"
  linkedin: "https://in.linkedin.com/in/navneethakrishnan"
  github: "https://www.github.com/navneet-suresh"
